### ISSUE TITLE
ExecutePreprocessor needs to accept timeout parameter

### ISSUE THREAD

**Issue by s-moran** [takluyver/nbparameterise#12]
In code.py:

https://github.com/takluyver/nbparameterise/blob/9ab986308eb25d81f5ad3241a0b8a01afca57762/nbparameterise/code.py#L107

The call to ExecutePreprocessor should accept timeout parameter otherwise long-running notebooks will timeout.

**Comment by takluyver** [comment]
I'm working towards making execution off by default, and probably eventually removing it altogether. So if you need to pass any other parameters, just get the notebook object and execute it separately. :-)

**Comment by s-moran** [comment]
> I'm working towards making execution off by default, and probably eventually removing it altogether. So if you need to pass any other parameters, just get the notebook object and execute it separately. :-)

Ah yes, that makes sense. In that case, we can probably close this issue :)

**Comment by takluyver** [comment]
Thanks :slightly_smiling_face:
