### ISSUE TITLE
Can I send complex object as a parameter

### ISSUE THREAD

**Issue by ghuname** [takluyver/nbparameterise#15]
If I have a notebook with first cell as:
`COMPLEX_OBJ = None`

Now if I use:

```
class ComplexObj:
    ... some complex properties and methods

complex_obj = ComplexObj()

orig_parameters = extract_parameters(nb)
params = parameter_values(orig_parameters, COMPLEX_OBJ=complex_obj)
new_nb = replace_definitions(nb, params)
```

I get an error in notebook saying: 
`NameError: name 'COMPLEX_OBJ' is not defined`

Looks like that in part of the code:

```
def extract_definitions(cell):
    cell_ast = ast.parse(cell)
    for assign in astsearch.ASTPatternFinder(definition_pattern).scan_ast(cell_ast):
        yield Parameter(assign.targets[0].id, *type_and_value(assign.value)
```

`astsearch.ASTPatternFinder(definition_pattern).scan_ast(cell_ast)` is not taking in account my parameter probably because it is not one of these:

```
def type_and_value(node):
    if isinstance(node, ast.Num):
        # int or float
        return type(node.n), node.n
    elif isinstance(node, ast.Str):
        return str, node.s
    elif isinstance(node, ast.NameConstant) and (node.value in (True, False)):
        return (bool, node.value)
    elif isinstance(node, ast.List):
        return (list, [type_and_value(n)[1] for n in node.elts])
    elif isinstance(node, ast.Dict):
        return (dict, {type_and_value(node.keys[i])[1]: type_and_value(node.values[i])[1] for i in range(len(node.keys))})

    raise NotImplementedError()
```

Is there any workaround?

**Comment by takluyver** [comment]
Not really, I'm afraid. The set of types you can use as parameters is basically the same as the types in JSON.

Complex objects are necessarily made up of simple ones, so you could have a group of simple parameters, and then use them to construct a complex object later on. Or feel free to use nbparameterise as inspiration to make a tool that does something else.

**Comment by ghuname** [comment]
@takluyver Thanks for confirmation.
I had to extract the logic for handling parameters to common place, so everyone will get simple parameters, than call the common logic with them in order to get proper starting point.
It works, and it is not that bad.
Best regards.

**Comment by takluyver** [comment]
:+1:
