### ISSUE TITLE
Version not found for pip install

### ISSUE THREAD

**Issue by smith6jt-cop** [takluyver/nbparameterise#18]
Trying to install in conda environment (yaml file here: https://github.com/ntakata/flexible-annotation-atlas).

pip install nbparameterize returns

Could not find a version that satisfies the requirement nbparameterize (from versions: )
No matching distribution found for nbparameterize

**Comment by takluyver** [comment]
nbparameterise with an s. Sometimes I rebel a bit against American spellings. :wink:

**Comment by smith6jt-cop** [comment]
Thank you!

**Comment by smith6jt-cop** [comment]
Haha!  What a mistake for me to make!

Thanks,

Justin Smith, PhD
Research Associate
The de Kloet/Krause Research Group
Department of Pharmacodynamics
McKnight Brain Institute
College of Pharmacy
University of Florida
