### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by billsanto** [takluyver/nbparameterise#4]
I had a cell exceeding the default timeout and was able to get around it by adding timeout=-1 to replace_definitions() and timeout=timeout to ExecutePreprocessor().

**Comment by takluyver** [comment]
That makes sense, but rather than re-exposing the options of ExecutePreprocessor as parameters to `replace_definitions()`, I think I'd encourage people to use `execute=False` and do the execution as a separate step. Maybe we can make a more convenient API for executing a notebook.

**Comment by takluyver** [comment]
I've added a convenience function to nbconvert in PR jupyter/nbconvert#573

**Comment by billsanto** [comment]
Thanks--I will need to take another look at it.  But I'd be interested to see an example of how to do that.

**Comment by takluyver** [comment]
The idea is that instead of doing this

```python
nb = replace_definitions(..., execute=True, timeout=-1)
```

You'd do this:

```python
nb = replace_definitions(..., execute=False)
nb = executenb(nb, timeout=-1)
```

**Comment by billsanto** [comment]
That's helpful.  Meanwhile, I reverted to the following:
`new_nb = replace_definitions(nb, params, execute=False)`
`new_nb, resources = ClearOutputPreprocessor().preprocess(new_nb, resources={})`
`new_nb, resources = ExecutePreprocessor(timeout=timeout_secs).preprocess(new_nb, resources={})`

**Comment by takluyver** [comment]
Great - closing this as we have both something that works now, and a plan for improving things.
