### ISSUE TITLE
nbparameterise in pypi installs with warning

### ISSUE THREAD

**Issue by harschware** [takluyver/nbparameterise#5]
$ python3 -m pip install nbparameterise
     ---> Running in 5c44c3fc4ac4
    Collecting nbparameterise
      Downloading nbparameterise-0.1-py3-none-any.whl
      Package nbparameterise has an invalid Requires-Python entry 3 - Invalid specifier: '3'

**Comment by takluyver** [comment]
Thanks, this should be fixed with version 0.2.
