### ISSUE TITLE
The option of using double-quotes instead of single-quotes

### ISSUE THREAD

**Issue by dnk8n** [takluyver/nbparameterise#8]
Bit of a pedantic request, I know!

However, I follow [PEP8: String Quotes](https://www.python.org/dev/peps/pep-0008/#string-quotes) where it suggests to 

> Pick a rule and stick to it.

In using this package I only see single quotes used in the parameters that are overloaded. Is there an option to use double quotes? If it could, that would mean that my styling guide could be honoured.

Also on another note (that is probably outside of what you expect to maintain), if double quotes could be supported, languages like Julia for example could be supported with almost no adjustment (I tested it out by copying and pasting the `python.py` codedriver and renaming it to `julia.py`)

The only reason it fails is because of the single quotes.

```
>>> new_nb = replace_definitions(nb, params)


Starting kernel event loops.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/src/nbparameterise/code.py", line 98, in replace_definitions
    nb, resources = ExecutePreprocessor().preprocess(nb, resources)
  File "/opt/conda/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 262, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/opt/conda/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/opt/conda/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 286, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
param1 = 'dummy1'
param2 = 'dummy2'
param3 = 'dummy3'
param4 = 'dummy4'
------------------

syntax: invalid character literal

LoadError: syntax: invalid character literal
```

**Comment by takluyver** [comment]
It uses whatever the [repr()](https://docs.python.org/3/library/functions.html#repr) function gives. For the basic types involved here (strings, numbers, bool), the repr always works as a Python expression which can be eval-ed to get the same value. To do anything else for strings, we'd have to implement a bunch of code to handle character escapes (like `\"` and `\n`) that `repr()` does for us.

So for Python code, not really. It would mean replacing an efficient built-in function which is basically guaranteed to be correct with a reimplementation which would probably have some bugs. And if it's an option, there's extra complexity to control it.

If you want to add another language driver, e.g. for Julia, you need a parser and a function to convert the supported basic types to an expression in that language. And they need to be accessible from Python somehow - whether that means reimplementing them, calling them through a foreign-function-interface, or running subprocesses.

I can see it's attractive to borrow the Python functionality for another language, but it will break e.g. on Julia's `true`and `false` (Python capitalises them). I probably wouldn't accept a pull request relying on this, unless there's a language that has almost exactly the same syntax as python.

**Comment by dnk8n** [comment]
Well, there is pyjulia... Could that aid us? Might spend some time to see if I could get it right, developing a Julia code driver.

**Comment by takluyver** [comment]
Yup, if Julia's parsing functionality and the equivalent of `repr()` are exposed as Julia functions, then I'd expect that pyjulia would work to call them from Python.

**Comment by takluyver** [comment]
Closing this as I've said no to changing string styles for Python. Drivers for other languages are still welcome in principle.
